### ISSUE TITLE
Publish to `crates.io`

### ISSUE THREAD

**Issue by filiptibell** [jkawamoto/ctranslate2-rs#21]
It seems that this crate is not published to `crates.io`, is this intentional? Would you be able to publish it there so we don't have to depend on `ctranslate2-rs` as a git dependency?
Using a git dependency prevents us from publishing our own crate.

**Comment by jkawamoto** [comment]
Since this library is an experimental project and not well-tested, I haven’t published it to crates.io yet. However, I’d like to do so once I merge the current PRs.

**Comment by jkawamoto** [comment]
I've published this crate on crates.io, and it's now available at https://crates.io/crates/ct2rs.
