### ISSUE TITLE
Support for Intel MKL

### ISSUE THREAD

**Issue by filiptibell** [jkawamoto/ctranslate2-rs#23]
I have been experimenting with getting Intel MKL support working on my fork of this repo (https://github.com/filiptibell/ctranslate2-rs) and have been successful by adding a dependency on `intel-mkl-src` and adding a `extern crate` directive at the crate root.

Would you be open to adding this to your crate?

**Comment by jkawamoto** [comment]
Your proposed changes look nice. Please feel free to open a PR.
