### ISSUE TITLE
Support for CUDA

### ISSUE THREAD

**Issue by filiptibell** [jkawamoto/ctranslate2-rs#24]
Similar to #23 , would you be open to adding support for building for CUDA? I have not yet figured out how to do this (don't have much experience with cc/cxx/build scripts) but this would be great for deploying on infra such as HF Inference Endpoints.

**Comment by jkawamoto** [comment]
It would be nice if we supported CUDA. However, I'm a Mac user, and testing with NVIDIA's GPUs is not easy for me...

**Comment by filiptibell** [comment]
It seems like [bindgen_cuda](https://github.com/Narsil/bindgen_cuda) has some logic for finding proper CUDA paths to link and it can probably be added as an optional dependency similar to `intel-mkl-src` in #23 . It needs an attached gpu to build but seems like that is also pretty common. I can take a look at this in a week or so
