### ISSUE TITLE
Add support for Whisper Large v3 Model

### ISSUE THREAD

**Issue by solaoi** [jkawamoto/ctranslate2-rs#81]
# Whisper Large v3 missing `mel_filters` in `preprocessor_config.json`

## Issue Description

Unlike the Tiny model, Whisper Large v3 doesn't include `mel_filters` in its `preprocessor_config.json` file.
Reference: [Whisper Large v3 preprocessor_config.json](https://huggingface.co/openai/whisper-large-v3/blob/main/preprocessor_config.json)

This omission causes the following error when attempting to use the model with `ctranslate2-rs`:

```
Error: missing field `mel_filters`
```

## Potential Solution

The `faster-whisper` library, which implements ctranslate2, addresses this issue with the following approach:

```python
model.feature_extractor.mel_filters = model.feature_extractor.get_mel_filters(
    model.feature_extractor.sampling_rate,
    model.feature_extractor.n_fft,
    n_mels=128
)
```

Reference: [faster-whisper GitHub issue #547](https://github.com/SYSTRAN/faster-whisper/issues/547)

**Comment by jkawamoto** [comment]
Thanks for reporting this issue. #82 will fix it.

**Comment by solaoi** [comment]
@jkawamoto 
Thank you for the prompt fix!
I've tested it, and it's working perfectly now.
